
export const projectCategories = [
    "Accounting & Legal Tech",
    "Adventure & Eco-tourism",
    "Affordable Housing",
    "Agriculture & AgriTech",
    "AI-powered",
    "AI-Powered in Construction Management",
    "Agri-Inputs (Fertilizer, Seeds, Irrigation)",
    "Agroforestry & Climate-Resilient Projects",
    "Aquaculture & Fisheries",
    "Arts, Culture & Heritage Preservation",
    "Automotive & E-Mobility Components",
    "Aviation & Drones",
    "Beverage Brands (Water, Juices, Alcoholic)",
    "Blockchain-enabled",
    "Business Process Outsourcing (BPO)",
    "Carbon Capture & Offsetting",
    "Circular Consumer Products (Reuse/Repair)",
    "Clean Cooking Solutions",
    "Climate Action Projects",
    "Clinics, Hospitals & Labs",
    "Commercial & Retail Spaces",
    "Construction",
    "Construction Materials / Prefab Housing",
    "Consumer Goods & Retail",
    "Corporate Learning Solutions",
    "Cosmetics & Personal Care",
    "Creative Economy & Media",
    "Crop Production & Processing",
    "Crowdfunding & Impact Investing Platforms",
    "Cultural / Heritage Tourism",
    "Deep Tech & R&D",
    "Digital Health / Wearables",
    "Digital Media & Influencer Platforms",
    "ESG, Impact & Community",
    "EV Charging Networks",
    "EdTech Applications",
    "Education, Skills & Human Capital",
    "Electronics Assembly & Consumer Goods",
    "Energy & Environment",
    "Energy Minerals (Lithium, Cobalt, etc.)",
    "Energy Storage & Battery Recycling",
    "Expansion / Scale-Up Stage",
    "Fashion & Apparel",
    "Film & TV Production",
    "Financial & Business Services",
    "Financial Inclusion",
    "Fintech",
    "Fleet Management Systems",
    "Food & Beverage",
    "Food Delivery Platforms",
    "Food Manufacturing",
    "Food Processing & Cold Chain",
    "Food Waste Reduction / Upcycling",
    "Furniture & Home Goods",
    "Gaming & Esports",
    "Gender Inclusion & Youth Projects",
    "Green/Low Carbon",
    "Green Buildings & LEED Projects",
    "Green Manufacturing (Low-carbon production)",
    "Health & Education Access",
    "Health, Wellness & Biotechnology",
    "Health Insurance / HMOs",
    "High Growth / Export-oriented",
    "Hotels & Resorts",
    "Impact Enterprises (SDG-aligned)",
    "Incubators & Accelerators",
    "Inclusion & Youth Empowerment",
    "Industrial Automation & Robotics",
    "Industrial Parks / Logistics Hubs",
    "Insurance & Risk Management",
    "Investment Funds & Venture Studios",
    "Lifestyle Brands & E-commerce Stores",
    "Livestock & Poultry",
    "Local Impact / Community-driven",
    "Local Artisans & Cultural Products",
    "Manufacturing & Industry",
    "Maritime & Port Services",
    "Medical Equipment & Supplies",
    "Mental Health & Wellness",
    "Microfinance & Cooperative Funds",
    "Mineral Processing & Refining",
    "Mining & Natural Resources",
    "Music & Entertainment Platforms",
    "NGO / Foundation-Led Projects",
    "Nutraceuticals & Supplements",
    "Organic & Sustainable Agriculture",
    "Packaging & Materials Innovation",
    "Pharmaceuticals & Biotech",
    "Plant-based & Alternative Proteins",
    "Plastic Recycling & Circular Economy ♻️",
    "Product Prototyping & IP Development",
    "Public Infrastructure PPPs",
    "Public Sector & Social Impact",
    "Public Transport Modernization",
    "Publishing & Content Studios",
    "Real Estate & Infrastructure",
    "Renewable Energy (Solar, Hydro, Wind, Biomass)",
    "Research, Innovation & Startups",
    "Residential Development",
    "Responsible Sourcing / Traceability",
    "Restaurants & Franchises",
    "Ride-Hailing & Logistics",
    "Rural Development",
    "Schools & Universities",
    "Small-scale Mining Formalization",
    "Smart Farming / Drones / IoT",
    "Smart Governance / eGov",
    "Smart Grids & Mini-Grids",
    "Technology & Digital Platforms",
    "Tourism & Hospitality",
    "Tourism, Hospitality & Leisure",
    "Transport & Tour Operators",
    "Travel Agencies & Platforms",
    "University Spin-offs",
    "Urban Regeneration & Smart Cities",
    "Vocational & Technical Training",
    "Waste Management",
    "Waste-to-Energy / Biogas",
    "Water & Land Rehabilitation",
    "Water Treatment & Purification",
    "Women-founded",
    "Women-led Enterprises",
    "Workforce Development Programs",
    "Youth-led",
    "Youth Empowerment Ventures"
];
