
'use client';

import Header from "@/components/header";
import Footer from "@/components/footer";
import { useEffect, useState } from "react";

export default function RiskDisclosurePage() {
  const [lastUpdated, setLastUpdated] = useState('');

  useEffect(() => {
    // This will only run on the client, after hydration
    setLastUpdated(new Date().toLocaleDateString());
  }, []);

  return (
    <div className="flex flex-col min-h-screen">
      <Header />
      <main className="flex-grow container mx-auto px-4 py-12">
        <div className="prose max-w-none">
          <h1 className="text-4xl font-bold font-headline mb-8">Risk Disclosure</h1>

          <p><strong>Last Updated:</strong> {lastUpdated || '...'}</p>

          <p>
            Investing in early-stage businesses, startups, and other projects listed on 3JN CrowdFunding ("the platform") involves significant risks. Before making any investment, you should carefully consider the risks summarized below. This is not an exhaustive list of all possible risks.
          </p>

          <h2 className="text-2xl font-bold font-headline mt-8">1. Risk of Loss of Capital</h2>
          <p>
            Most new businesses fail. There is a high probability that you will lose your entire investment. You should not invest more money than you can afford to lose without impacting your lifestyle.
          </p>

          <h2 className="text-2xl font-bold font-headline mt-8">2. Illiquidity</h2>
          <p>
            Investments made through the platform are highly illiquid. There is currently no secondary market for the shares or royalty rights you purchase, and none may ever develop. This means you may not be able to sell your investment until the company is acquired by another company or conducts an Initial Public Offering (IPO). This can take many years and may never happen.
          </p>

          <h2 className="text-2xl font-bold font-headline mt-8">3. No Guarantee of Returns</h2>
          <p>
            Any financial projections, return on investment (ROI) forecasts, or valuation information provided by project owners or generated by our AI tools are for illustrative purposes only. They are not a guarantee of future performance. Actual results can vary significantly.
          </p>

          <h2 className="text-2xl font-bold font-headline mt-8">4. Dilution</h2>
          <p>
            For equity investments, any future fundraising rounds by the company will likely dilute your ownership percentage. This means your proportional stake in the company will decrease. While this may be accompanied by an increase in the company's valuation, it is not guaranteed.
          </p>
          
          <h2 className="text-2xl font-bold font-headline mt-8">5. Dividends & Royalty Payments are Not Guaranteed</h2>
          <p>
            Companies are not obligated to pay dividends to equity shareholders. For royalty-based investments, payments are dependent on the company's revenue and profitability. If the company fails to generate sufficient revenue, you may not receive any royalty payments.
          </p>

          <h2 className="text-2xl font-bold font-headline mt-8">6. Lack of Professional Advice</h2>
          <p>
            3JN CrowdFunding is not a broker-dealer, investment advisor, or financial advisor. We do not provide any investment advice, legal advice, or tax advice. You are solely responsible for conducting your own due diligence and should consult with your own professional advisors before making any investment.
          </p>

          <h2 className="text-2xl font-bold font-headline mt-8">7. Acknowledgment</h2>
          <p>
            By using our Services to make an investment, you acknowledge that you have read, understood, and accepted these risks.
          </p>
        </div>
      </main>
      <Footer />
    </div>
  );
}
